name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main # Replace with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired AWS region

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --no-deps -r awsRequirements.txt -t .

      - name: Create Lambda deployment package
        run: |
          zip -r deployment-package.zip .

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name alpacaTrading \
            --zip-file fileb://deployment-package.zip
