name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main # Replace with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired AWS region

      - name: Create Lambda deployment package
        run: |
          zip -r deployment-package.zip . -x "README.md" "workflow.jpg" "test.py" "requirements.txt" "main.py" ".gitignore" "images/\*" "event.json" "main_status.py"

      - name: Deploy to AWS Lambda AlpacaTrading
        run: |
          aws lambda update-function-code \
            --function-name alpacaTrading \
            --zip-file fileb://deployment-package.zip

      - name: Deploy to AWS Lambda AlpacaTradingStatus
        run: |
          aws lambda update-function-code \
            --function-name alpacaTradingStatus \
            --zip-file fileb://deployment-package.zip
